name: shoes_app
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^3.0.3
  shared_preferences: ^2.0.20
  cached_network_image: ^3.2.3
  flutter_svg:
  flutter_svg_provider: ^1.0.3
  smooth_page_indicator: ^1.0.1
  pin_code_fields: ^7.4.0
  sms_autofill: ^2.3.0
  pin_input_text_field: ^4.5.0
  url_launcher: ^6.1.10
  carousel_slider: ^4.2.1
  dotted_border: 2.0.0+3
  intl: ^0.18.0
  country_list_pick: ^1.0.1+6
  flutter_rating_bar: ^4.0.1
  expandable: ^5.0.1
  flutter_launcher_icons: ^0.12.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: PNU
      fonts:
        - asset: assets/fonts/ArbFONTS-PNU-Bold.ttf
        - asset: assets/fonts/ArbFONTS-PNU-Light.ttf
        - asset: assets/fonts/ArbFONTS-PNU-Medium.ttf
        - asset: assets/fonts/ArbFONTS-PNU-Regular.ttf
